<a href="https://colab.research.google.com/github/PotlachervuSrilatha/Numpy/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
# NumPy (also called Numerical Python) is a highly flexible, optimized, open-source package meant for array processing.
# It provides tools for delivering high-end performance while dealing with N-dimensional powerful array objects.
# It is also beneficial for performing scientific computations, mathematical, and logical operations,
# sorting operations, I/O functions, basic statistical and linear algebra-based operations along with random simulation and broadcasting functionalities.
#  Due to the vast range of capabilities, NumPy has become very popular and is the most preferred package.


In [110]:
# # Creating Numpy Array
# Numpy stands for Numerical python and is the core library for numeric and scientific computing
# it consists of multi-dimensional array objects and a collection of routiness for processing those arrays

In [111]:
# SINGLE -DIMENSIONAL ARRAY

In [112]:
import numpy as np

In [113]:
n1=np.array([1,2,3,4,5])
print(n1)

[1 2 3 4 5]


In [114]:
type(n1)

numpy.ndarray

In [115]:
# Multi-Dimensional Array

In [116]:
n2=np.array([[1,2,3,4,5],
         [4,5,6,7,8]])

In [117]:
n2

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [118]:
type(n2)

numpy.ndarray

In [119]:
# Three-Dimensional array


In [120]:
import numpy as np

n1 = [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]]
numpy_arr = np.array(n1)
numpy_arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]])

In [121]:
# INITIALIZING NUMPY ARRAY

In [122]:
# initializing numpy array with zeros

In [123]:
import numpy as np

In [124]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [125]:
n1=np.zeros((5,5))

In [126]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [127]:
# initializing numpy array with same number
#np.full

In [128]:
import numpy as np
n1= np.full((5,5),10)
n1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [129]:
# initializing numpy array within a range
#np.arange

In [130]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [131]:
n1=np.arange(10,50,7)

In [132]:
n1

array([10, 17, 24, 31, 38, 45])

In [133]:
n1=np.arange(100,200,10)
n1

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [134]:
n1=np.arange(100,201,50)
n1

array([100, 150, 200])

In [135]:
# initializing numpy array with random numbers
# np.random.randomint

In [136]:
n1=np.random.randint(1,100,35)
n1

array([ 3, 35, 10, 67, 33, 57, 28, 69, 28, 51, 98, 61, 61, 90, 85, 64,  2,
       18, 51,  8, 25,  7, 59, 31, 84, 19, 86,  4,  8,  3, 17, 96, 91, 69,
       54])

In [137]:
n1=np.random.randint(50,100,10)
n1

array([73, 52, 85, 54, 98, 50, 63, 78, 51, 67])

In [138]:
# NUMPY SHAPE
#CHECKING THE SHAPE OF NUMPY ARRAYS

In [139]:
import numpy as np
n1=np.array([[1,2,3,4,5],[4,5,6,7,8,]])
n1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [140]:
n1.shape

(2, 5)

In [141]:
n1.shape=(5,2)
n1.shape
n1

array([[1, 2],
       [3, 4],
       [5, 4],
       [5, 6],
       [7, 8]])

In [142]:
# JOINING NUMPY ARRAYS
# np.vstack()
# np.hstack()
# np.column_stack()

In [143]:
import numpy as np
n1=np.array([10,20,30,40,50])
n2=np.array([60,70,80,90,100])

In [144]:
np.vstack((n1,n2))

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [145]:
np.vstack((n2,n1))

array([[ 60,  70,  80,  90, 100],
       [ 10,  20,  30,  40,  50]])

In [146]:
np.hstack((n1,n2))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [147]:
np.hstack((n2,n1))

array([ 60,  70,  80,  90, 100,  10,  20,  30,  40,  50])

In [148]:
np.column_stack((n1,n2))

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

In [149]:
np.column_stack((n2,n2))

array([[ 60,  60],
       [ 70,  70],
       [ 80,  80],
       [ 90,  90],
       [100, 100]])

In [150]:
# NUMPY INTERSECTION & dIFFERENCE

In [151]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [152]:
np.intersect1d(n1,n2)


array([50, 60])

In [153]:
np.setdiff1d(n1,n2)


array([10, 20, 30, 40])

In [154]:
np.intersect1d(n2,n1)


array([50, 60])

In [155]:
#ddition of numpy arrays

In [156]:
n1=np.array([10,20,30])
n2=np.array([30,40,50])
np.sum([n1,n2])

180

In [157]:
n1=([10,20,30])
n2=([30,40,50])

In [158]:
np.sum([n1,n2])

180

In [159]:
np.sum([n1,n2],axis=0)

array([40, 60, 80])

In [160]:
np.sum([n1,n2],axis=1)

array([ 60, 120])

In [161]:
#NUMPY ARRAY MATHEMATICS

In [162]:
#BASIC ADDITION

In [163]:
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [164]:
#BASIC SUBTRACTION

In [165]:
n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [166]:
#BASIC MULTIPLICATION

In [167]:
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [168]:
#BASIC DIVISION

In [169]:
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [170]:
n1=np.array([10,20,30])
np.mean(n1)


20.0

In [171]:
np.median(n1)

20.0

In [172]:
np.std(n1)

8.16496580927726

In [173]:
from scipy.stats import mode
mode(n1)

ModeResult(mode=10, count=1)

In [175]:
#Numpy matrix

In [176]:
n1=np.array

In [177]:
import numpy as np
n1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
n1[0]

array([1, 2, 3])

In [179]:
n1[1]

array([4, 5, 6])

In [180]:
n1[2]

array([7, 8, 9])

In [181]:
n1[:1]

array([[1, 2, 3]])

In [182]:
n1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
#NUMPY MATRIX TRANSPOSE

In [ ]:
n1

In [184]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [185]:
#Numpy matrix multiplication

In [186]:
n1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [187]:
n1.dot(n2)

array([260, 620, 980])

In [188]:
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
n2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [189]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [190]:
#SAVING NUMPY ARRAY

In [191]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
np.save("my_numpy",n1)

In [192]:
#LOADING NUMPY ARRAY

In [193]:
n2=np.load("my_numpy.npy")
n2

array([10, 20, 30, 40, 50, 60])