<a href="https://colab.research.google.com/github/PotlachervuSrilatha/Numpy/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# NumPy (also called Numerical Python) is a highly flexible, optimized, open-source package meant for array processing.
# It provides tools for delivering high-end performance while dealing with N-dimensional powerful array objects.
# It is also beneficial for performing scientific computations, mathematical, and logical operations,
# sorting operations, I/O functions, basic statistical and linear algebra-based operations along with random simulation and broadcasting functionalities.
#  Due to the vast range of capabilities, NumPy has become very popular and is the most preferred package.


In [3]:
# # Creating Numpy Array
# Numpy stands for Numerical python and is the core library for numeric and scientific computing
# it consists of multi-dimensional array objects and a collection of routiness for processing those arrays

In [4]:
# SINGLE -DIMENSIONAL ARRAY

In [5]:
import numpy as np

In [6]:
n1=np.array([1,2,3,4,5])
print(n1)

[1 2 3 4 5]


In [7]:
type(n1)

numpy.ndarray

In [8]:
# Multi-Dimensional Array

In [9]:
n2=np.array([[1,2,3,4,5],
         [4,5,6,7,8]])

In [10]:
n2

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [11]:
type(n2)

numpy.ndarray

In [12]:
# INITIALIZING NUMPY ARRAY

In [13]:
# initializing numpy array with zeros

In [14]:
import numpy as np

In [15]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [16]:
n1=np.zeros((5,5))

In [17]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# initializing numpy array with same number
#np.full

In [19]:
import numpy as np
n1= np.full((5,5),10)
n1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [20]:
# initializing numpy array within a range
#np.arange

In [21]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
n1=np.arange(10,50,7)

In [23]:
n1

array([10, 17, 24, 31, 38, 45])

In [24]:
n1=np.arange(100,200,10)
n1

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [25]:
n1=np.arange(100,201,50)
n1

array([100, 150, 200])

In [26]:
# initializing numpy array with random numbers
# np.random.randomint

In [27]:
n1=np.random.randint(1,100,35)
n1

array([13, 17, 99, 55, 38, 43, 59, 21, 38, 98, 19, 11, 99, 19, 65, 62, 19,
       73, 49, 74, 62, 30, 25,  7, 32, 95, 24, 70, 84, 59, 93, 16, 71, 61,
       26])

In [28]:
n1=np.random.randint(50,100,10)
n1

array([97, 71, 83, 88, 74, 98, 79, 53, 83, 78])

In [29]:
# NUMPY SHAPE
#CHECKING THE SHAPE OF NUMPY ARRAYS

In [30]:
import numpy as np
n1=np.array([[1,2,3,4,5],[4,5,6,7,8,]])
n1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [31]:
n1.shape

(2, 5)

In [32]:
n1.shape=(5,2)
n1.shape
n1

array([[1, 2],
       [3, 4],
       [5, 4],
       [5, 6],
       [7, 8]])

In [33]:
# JOINING NUMPY ARRAYS
# np.vstack()
# np.hstack()
# np.column_stack()

In [34]:
import numpy as np
n1=np.array([10,20,30,40,50])
n2=np.array([60,70,80,90,100])

In [35]:
np.vstack((n1,n2))

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [36]:
np.vstack((n2,n1))

array([[ 60,  70,  80,  90, 100],
       [ 10,  20,  30,  40,  50]])

In [37]:
np.hstack((n1,n2))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [38]:
np.hstack((n2,n1))

array([ 60,  70,  80,  90, 100,  10,  20,  30,  40,  50])

In [39]:
np.column_stack((n1,n2))

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

In [40]:
np.column_stack((n2,n2))

array([[ 60,  60],
       [ 70,  70],
       [ 80,  80],
       [ 90,  90],
       [100, 100]])

In [41]:
# NUMPY INTERSECTION & dIFFERENCE

In [42]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [43]:
np.intersect1d(n1,n2)


array([50, 60])

In [44]:
np.setdiff1d(n1,n2)


array([10, 20, 30, 40])

In [45]:
np.intersect1d(n2,n1)


array([50, 60])

In [46]:
#ddition of numpy arrays

In [47]:
n1=np.array([10,20,30])
n2=np.array([30,40,50])
np.sum([n1,n2])

180

In [48]:
n1=([10,20,30])
n2=([30,40,50])

In [49]:
np.sum([n1,n2])

180

In [50]:
np.sum([n1,n2],axis=0)

array([40, 60, 80])

In [51]:
np.sum([n1,n2],axis=1)

array([ 60, 120])

In [52]:
#NUMPY ARRAY MATHEMATICS

In [53]:
#BASIC ADDITION

In [54]:
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [55]:
#BASIC SUBTRACTION

In [56]:
n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [57]:
#BASIC MULTIPLICATION

In [58]:
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [59]:
#BASIC DIVISION

In [60]:
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [61]:
n1=np.array([10,20,30])
np.mean(n1)


20.0

In [62]:
np.median(n1)

20.0

In [63]:
np.std(n1)

8.16496580927726

In [65]:
np.median(n1)

20.0

In [67]:
from scipy.stats import mode
mode(n1)

ModeResult(mode=10, count=1)